name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ttkbootstrap

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Notify GitHub of job status
      if: always()
      uses: actions/github-script@v5
      with:
        script: |
          github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: github.context.sha,
            state: 'success',
            description: 'Test completed successfully',
            context: 'test'
          })